#!/bin/sh
mkdir -p /iso
mkdir -p /net/.img
mkdir -p /net/.scripts
cd /iso
curl -Lo /net/.scripts/winpe.iso https://nash-central.com/projects/bcdbooter/winpe.iso
curl -L https://jenux.dev/get\?tripple-installer.iso|bsdtar -x
export loopdev=`losetup -P -r --show -f Jenux-\`date +%Y.%m.%d\`-*.iso`
mount $loopdev"p3" /mnt
mount $loopdev"p2" /mnt/EFI
cp -rf /mnt/* /net
cp -rf /mnt/pxe/.{scripts,services} /net
cp -rf /mnt/pxe/* /net
cp /net/.services/* /lib/systemd/system
umount /mnt/EFI /mnt
losetup -d $loopdev
chown -R root:root /net
chmod -R 755 /net
systemctl enable pxe nbdproc
